/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Dirent {
  name: string
  path: string
  isDir: boolean
}

export declare function readdir(path: string, options?: ReaddirOptions | undefined | null): Promise<unknown>

export interface ReaddirOptions {
  skipHidden?: boolean
  concurrency?: number
  recursive?: boolean
}

export declare function readdirSync(path: string, options?: ReaddirOptions | undefined | null): Array<Dirent>
