/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Dirent {
  readonly name: string
  readonly parentPath: string
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
  get path(): string
}

export declare function glob(pattern: string, options?: GlobOptions | undefined | null): Promise<unknown>

export interface GlobOptions {
  cwd?: string
  withFileTypes?: boolean
  exclude?: Array<string>
  concurrency?: number
  gitIgnore?: boolean
}

export declare function globSync(
  pattern: string,
  options?: GlobOptions | undefined | null,
): Array<string> | Array<Dirent>

export declare function readdir(path: string, options?: ReaddirOptions | undefined | null): Promise<unknown>

/** * Reads the contents of a directory.
 * @param {string | Buffer | URL} path
 * @param {string | {
 *   encoding?: string;
 *   withFileTypes?: boolean;
 *   recursive?: boolean;
 *   }} [options]
 * @param {(
 *   err?: Error,
 *   files?: string[] | Buffer[] | Dirent[]
 * ) => any} callback
 * @returns {void}
 */
export interface ReaddirOptions {
  skipHidden?: boolean
  concurrency?: number
  recursive?: boolean
  withFileTypes?: boolean
}

export declare function readdirSync(
  path: string,
  options?: ReaddirOptions | undefined | null,
): Array<string> | Array<Dirent>

export declare function rm(path: string, options?: RmOptions | undefined | null): Promise<unknown>

/** * Asynchronously removes files and
 * directories (modeled on the standard POSIX `rm` utility).
 * @param {string | Buffer | URL} path
 * @param {{
 *   force?: boolean;
 *   maxRetries?: number;
 *   recursive?: boolean;
 *   retryDelay?: number;
 *   }} [options]
 * @param {(err?: Error) => any} callback
 * @returns {void}
 */
export interface RmOptions {
  force?: boolean
  maxRetries?: number
  recursive?: boolean
  retryDelay?: number
  concurrency?: number
}

export declare function rmSync(path: string, options?: RmOptions | undefined | null): void
